name = "cell-router"
main = "index.js"
compatibility_date = "2024-01-01"
account_id = "5a6fef07a998d84ec047ef43d0543342"

[[durable_objects.bindings]]
name = "CELL_REGISTRY"
class_name = "CellRegistry"
script_name = "cell-router"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CellRegistry"]